export const ACCOUNT_BATCH_SIZE = 3

/* WALLET TYPES */
export const LEDGER = 'LEDGER'
export const MNEMONIC = 'MNEMONIC'
export const SINGLE_KEY = 'SINGLE_KEY'

export const IMPORT_MNEMONIC = 'IMPORT_MNEMONIC'
export const CREATE_MNEMONIC = 'CREATE_MNEMONIC'
export const IMPORT_SINGLE_KEY = 'IMPORT_SINGLE_KEY'
