export const WALLET_LIST = 'WALLET_LIST'
export const SWITCH_WALLET = 'SWITCH_WALLET'

export const UPDATE_BALANCE = 'UPDATE_BALANCE'

export const CONFIRM_MESSAGE = 'CONFIRM_MESSAGE'
export const CONFIRMED_MESSAGE = 'CONFIRMED_MESSAGE'

export const FETCHING_CONFIRMED_MESSAGES = 'FETCHING_CONFIRMED_MESSAGES'
export const FETCHED_CONFIRMED_MESSAGES_SUCCESS =
  'FETCHED_CONFIRMED_MESSAGES_SUCCESS'
export const FETCHED_CONFIRMED_MESSAGES_FAILURE =
  'FETCHED_CONFIRMED_MESSAGES_FAILURE'
export const FETCHING_NEXT_PAGE = 'FETCHING_NEXT_PAGE'
export const FETCHING_NEXT_PAGE_SUCCESS = 'FETCHING_NEXT_PAGE_SUCCESS'
export const FETCHING_NEXT_PAGE_FAILURE = 'FETCHING_NEXT_PAGE_FAILURE'

export const UPDATE_PROGRESS = 'UPDATE_PROGRESS'

export const SET_WALLET_TYPE = 'SET_WALLET_TYPE'
export const CREATE_WALLET_PROVIDER = 'CREATE_WALLET_PROVIDER'

export const ERROR = 'ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
