export const WALLET_LIST = 'WALLET_LIST';
export const SWITCH_ACCOUNT = 'SWITCH_ACCOUNT';
export const NEW_ACCOUNT = 'NEW_ACCOUNT';

export const UPDATE_BALANCE = 'UPDATE_BALANCE';

export const CONFIRM_MESSAGE = 'CONFIRM_MESSAGE';
export const CONFIRMED_MESSAGES = 'CONFIRMED_MESSAGES';

export const ERROR = 'ERROR';
