export const CONFIRM_MESSAGE = 'CONFIRM_MESSAGE'
export const CONFIRMED_MESSAGE = 'CONFIRMED_MESSAGE'

export const FETCHING_CONFIRMED_MESSAGES = 'FETCHING_CONFIRMED_MESSAGES'
export const FETCHED_CONFIRMED_MESSAGES_SUCCESS =
  'FETCHED_CONFIRMED_MESSAGES_SUCCESS'
export const FETCHED_CONFIRMED_MESSAGES_FAILURE =
  'FETCHED_CONFIRMED_MESSAGES_FAILURE'
export const FETCHING_NEXT_PAGE = 'FETCHING_NEXT_PAGE'
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES'

export const POPULATE_REDUX = 'POPULATE_REDUX'

export const RESET_STATE = 'RESET_STATE'
