export const WALLET_LIST = 'WALLET_LIST'
export const SWITCH_WALLET = 'SWITCH_WALLET'

export const UPDATE_BALANCE = 'UPDATE_BALANCE'

export const CONFIRM_MESSAGE = 'CONFIRM_MESSAGE'
export const CONFIRMED_MESSAGE = 'CONFIRMED_MESSAGE'

export const FETCHING_CONFIRMED_MESSAGES = 'FETCHING_CONFIRMED_MESSAGES'
export const FETCHED_CONFIRMED_MESSAGES_SUCCESS =
  'FETCHED_CONFIRMED_MESSAGES_SUCCESS'
export const FETCHED_CONFIRMED_MESSAGES_FAILURE =
  'FETCHED_CONFIRMED_MESSAGES_FAILURE'
export const FETCHING_NEXT_PAGE = 'FETCHING_NEXT_PAGE'
export const FETCHING_NEXT_PAGE_SUCCESS = 'FETCHING_NEXT_PAGE_SUCCESS'
export const FETCHING_NEXT_PAGE_FAILURE = 'FETCHING_NEXT_PAGE_FAILURE'

export const ERROR = 'ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const POPULATE_REDUX = 'POPULATE_REDUX'

export const SWITCH_NETWORK = 'SWITCH_NETWORK'

export const SELECT_MESSAGE = 'SELECT_MESSAGE'
