# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy - mainnet

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm test
      - run: npm run export
        env:
          LOTUS_NODE_JSONRPC: 'https://mainnet.glif.host'
          GRAPH_API_URL: 'graph.glif.host/query'
          EXPLORER_URL: 'https://explorer.glif.io'
          NODE_STATUS_API_KEY: 'm786191525-b3192b91db66217a44f7d4be'
          STATUS_API_ADDRESS: 'https://api.uptimerobot.com/v2/getMonitors'
          COIN_TYPE: 'f'
      - run: npm run publish:mainnet
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      - run: npm run store-ipfs
        env:
          WEB3_STORAGE_TOKEN: ${{ secrets.WEB3_STORAGE_TOKEN }}
